<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Things that are needed only for Gazebo (not the physical robot). These include sensor and controller plugin specifications -->
    <xacro:include filename="$(find go1_description)/urdfs/leg.transmission.xacro"/>
    <xacro:include filename="$(find go1_description)/urdfs/leg.gazebo.xacro"/>
    

    <xacro:macro name="leg" params="name mirror mirror_dae front_hind front_hind_dae load_force_sensors *origin">

        <joint name="${name}_haa_joint" type="revolute">
            <xacro:insert_block name="origin"/>
            <parent link="trunk"/>
            <child link="${name}_hip"/>
            <axis xyz="1 0 0"/>
            <dynamics damping="${damping}" friction="${friction}"/>
            <xacro:if value="${(mirror_dae == True)}">
                <!-- limit effort="${haa_torque_max}" velocity="${haa_velocity_max}" lower="${haa_min*PI/180.0}" upper="${haa_max*PI/180.0}"/ -->
                <limit effort="${haa_torque_max}" velocity="${haa_velocity_max}" lower="${haa_min}" upper="${haa_max}" />
            </xacro:if>
            <xacro:if value="${(mirror_dae == False)}">
                <!-- limit effort="${haa_torque_max}" velocity="${haa_velocity_max}" lower="${-haa_max*PI/180.0}" upper="${-haa_min*PI/180.0}"/ -->
                <limit effort="${haa_torque_max}" velocity="${haa_velocity_max}" lower="${-haa_max}" upper="${-haa_min}" />
            </xacro:if>            
        </joint>

        <link name="${name}_hip">
            <visual>
                <xacro:if value="${(mirror_dae == True) and (front_hind_dae == True)}">
                    <origin rpy="0 0 0" xyz="0 0 0"/>
                </xacro:if>
                <xacro:if value="${(mirror_dae == False) and (front_hind_dae == True)}">
                    <origin rpy="${PI} 0 0" xyz="0 0 0"/>
                </xacro:if>
                <xacro:if value="${(mirror_dae == True) and (front_hind_dae == False)}">
                    <origin rpy="0 ${PI} 0" xyz="0 0 0"/>
                </xacro:if>
                <xacro:if value="${(mirror_dae == False) and (front_hind_dae == False)}">
                    <origin rpy="${PI} ${PI} 0" xyz="0 0 0"/>
                </xacro:if>
                <geometry>
                    <mesh filename="package://go1_description/meshes/hip.dae" scale="1 1 1"/>
                </geometry>
                <!-- <material name="orange"/> -->
            </visual>
            <collision>
                <origin rpy="${PI/2.0} 0 0" xyz="0 0 0"/>
                <geometry>
                    <cylinder length="${hip_length}" radius="${hip_radius}"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${hip_com_x*front_hind} ${hip_com_y*mirror} ${hip_com_z}"/>
                <mass value="${hip_mass}"/>
                <inertia
                    ixx="${hip_ixx}" ixy="${hip_ixy*mirror*front_hind}" ixz="${hip_ixz*front_hind}"
                    iyy="${hip_iyy}" iyz="${hip_iyz*mirror}"
                    izz="${hip_izz}"/>       
            </inertial>
        </link>

        <joint name="${name}_haa_fixed" type="fixed">
            <origin rpy="0 0 0" xyz="0 ${(hip_offset)*mirror} 0"/>
            <parent link="${name}_hip"/>
            <child link="${name}_upperleg_shoulder"/>
        </joint>

        <!-- this link is only for collision -->
        <link name="${name}_upperleg_shoulder">
            <collision>
                <origin rpy="${PI/2.0} 0 0" xyz="0 0 0"/>
                <geometry>
                    <cylinder length="${upperleg_shoulder_length}" radius="${upperleg_shoulder_radius}"/>
                </geometry>
            </collision>
        </link>
        
        <!-- haa motor -->
        <joint name="${name}_haa_motor_joint" type="fixed">
            <xacro:if value="${(mirror_dae == False) and (front_hind_dae == True)}">
                <origin rpy="0 0 0" xyz="${haa_motor_offset_x} ${-haa_motor_offset_y} 0"/>
            </xacro:if>
            <xacro:if value="${(mirror_dae == True) and (front_hind_dae == True)}">
                <origin rpy="0 0 0" xyz="${haa_motor_offset_x} ${haa_motor_offset_y} 0"/>
            </xacro:if>
            <xacro:if value="${(mirror_dae == False) and (front_hind_dae == False)}">
                <origin rpy="0 0 0" xyz="${-haa_motor_offset_x} ${-haa_motor_offset_y} 0"/>
            </xacro:if>
            <xacro:if value="${(mirror_dae == True) and (front_hind_dae == False)}">
                <origin rpy="0 0 0" xyz="${-haa_motor_offset_x} ${haa_motor_offset_y} 0"/>
            </xacro:if>
            <parent link="trunk"/>
            <child link="${name}_haa_motor"/>         
        </joint>
        
        <link name="${name}_haa_motor">
            <!--visual>
                <origin rpy="0 ${PI/2.0} 0" xyz="0 0 0"/>
                <geometry>
                    <cylinder length="0.02" radius="0.035"/>
                </geometry>
                <material name="green"/>
            </visual>
            <collision>
                <origin rpy="0 ${PI/2.0} 0" xyz="0 0 0"/>
                <geometry>
                    <cylinder length="0.02" radius="0.035"/>
                </geometry>
            </collision -->
            <inertial>
                <origin rpy="0 0 0" xyz="${motor_com_x} ${motor_com_y} ${motor_com_z}"/>
                <mass value="${motor_mass}"/>
                <inertia
                    ixx="${motor_ixx}" ixy="${motor_ixy}" ixz="${motor_ixz}"
                    iyy="${motor_iyy}" iyz="${motor_iyz}"
                    izz="${motor_izz}"/>              
            </inertial>
         </link>
        
        

        <joint name="${name}_hfe_joint" type="revolute">
            <origin rpy="0 0 0" xyz="0 ${upperleg_offset*mirror} 0"/>
            <parent link="${name}_hip"/>
            <child link="${name}_upperleg"/>
            <axis xyz="0 1 0"/>
            <dynamics damping="${damping}" friction="${friction}"/>
            <!--limit effort="${hfe_torque_max}" velocity="${hfe_velocity_max}" lower="${hfe_min*PI/180.0}" upper="${hfe_max*PI/180.0}"/ -->
            <limit effort="${hfe_torque_max}" velocity="${hfe_velocity_max}" lower="${hfe_min}" upper="${hfe_max}"/>
        </joint>
        
        <!-- hfe motor -->
        <joint name="${name}_hfe_motor_joint" type="fixed">
            <xacro:if value="${(mirror_dae == False) and (front_hind_dae == True)}">
                <origin rpy="0 0 0" xyz="${hfe_motor_offset_x} ${-hfe_motor_offset_y} 0"/>
            </xacro:if>
            <xacro:if value="${(mirror_dae == True) and (front_hind_dae == True)}">
                <origin rpy="0 0 0" xyz="${hfe_motor_offset_x} ${hfe_motor_offset_y} 0"/>
            </xacro:if>
            <xacro:if value="${(mirror_dae == False) and (front_hind_dae == False)}">
                <origin rpy="0 0 0" xyz="${-hfe_motor_offset_x} ${-hfe_motor_offset_y} 0"/>
            </xacro:if>
            <xacro:if value="${(mirror_dae == True) and (front_hind_dae == False)}">
                <origin rpy="0 0 0" xyz="${-hfe_motor_offset_x} ${hfe_motor_offset_y} 0"/>
            </xacro:if>
            <parent link="${name}_upperleg"/>
            <child link="${name}_hfe_motor"/>         
        </joint>
        
        <link name="${name}_hfe_motor">
            <!--visual>
                <origin rpy="0 ${PI/2.0} 0" xyz="0 0 0"/>
                <geometry>
                    <cylinder length="0.02" radius="0.035"/>
                </geometry>
                <material name="green"/>
            </visual>
            <collision>
                <origin rpy="0 ${PI/2.0} 0" xyz="0 0 0"/>
                <geometry>
                    <cylinder length="0.02" radius="0.035"/>
                </geometry>
            </collision -->
            <inertial>
                <origin rpy="0 0 0" xyz="${motor_com_x} ${motor_com_y} ${motor_com_z}"/>
                <mass value="${motor_mass}"/>
                <inertia
                    ixx="${motor_ixx}" ixy="${motor_ixy}" ixz="${motor_ixz}"
                    iyy="${motor_iyy}" iyz="${motor_iyz}"
                    izz="${motor_izz}"/>              
            </inertial>
         </link>

        <link name="${name}_upperleg">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <xacro:if value="${mirror_dae == True}">
                        <mesh filename="package://go1_description/meshes/upperleg.dae" scale="1 1 1"/>
                    </xacro:if>
                    <xacro:if value="${mirror_dae == False}">
                        <mesh filename="package://go1_description/meshes/upperleg_mirror.dae" scale="1 1 1"/>
                    </xacro:if>
                </geometry>
                <!-- <material name="orange"/> -->
            </visual>
            <collision>
                <origin rpy="0 ${PI/2.0} 0" xyz="0 0 ${-upperleg_length/2.0}"/>
                <geometry>
                    <box size="${upperleg_length} ${upperleg_width} ${upperleg_height}"/>
                </geometry>      
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${upperleg_com_x} ${upperleg_com_y*mirror} ${upperleg_com_z}"/>
                <mass value="${upperleg_mass}"/>
                <inertia
                    ixx="${upperleg_ixx}" ixy="${upperleg_ixy*mirror}" ixz="${upperleg_ixz}"
                    iyy="${upperleg_iyy}" iyz="${upperleg_iyz*mirror}"
                    izz="${upperleg_izz}"/>       
            </inertial>
        </link>

        <joint name="${name}_kfe_joint" type="revolute">
            <origin rpy="0 0 0" xyz="0 0 ${-upperleg_length}"/>
            <parent link="${name}_upperleg"/>
            <child link="${name}_lowerleg"/>
            <axis xyz="0 1 0"/>
            <dynamics damping="${damping}" friction="${friction}"/>
            <!-- limit effort="${kfe_torque_max}" velocity="${kfe_velocity_max}" lower="${kfe_min*PI/180.0}" upper="${kfe_max*PI/180.0}"/ -->
            <limit effort="${kfe_torque_max}" velocity="${kfe_velocity_max}" lower="${kfe_min}" upper="${kfe_max}"/>
        </joint>

        <link name="${name}_lowerleg">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <mesh filename="package://go1_description/meshes/lowerleg.dae" scale="1 1 1"/>
                </geometry>
                <!-- <material name="orange"/> -->
            </visual>
            <collision>
                <origin rpy="0 ${PI/2.0} 0" xyz="0 0 ${-lowerleg_length/2.0}"/>
                <geometry>
                    <box size="${lowerleg_length} ${lowerleg_width} ${lowerleg_height}"/>
                </geometry>      
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${lowerleg_com_x} ${lowerleg_com_y} ${lowerleg_com_z}"/>
                <mass value="${lowerleg_mass}"/>
                <inertia
                    ixx="${lowerleg_ixx}" ixy="${lowerleg_ixy}" ixz="${lowerleg_ixz}"
                    iyy="${lowerleg_iyy}" iyz="${lowerleg_iyz}"
                    izz="${lowerleg_izz}"/>       
            </inertial>
        </link>
        
        <!-- kfe motor -->
        <joint name="${name}_kfe_motor_joint" type="fixed">
            <xacro:if value="${(mirror_dae == False) and (front_hind_dae == True)}">
                <origin rpy="0 0 0" xyz="${kfe_motor_offset_x} ${-kfe_motor_offset_y} 0"/>
            </xacro:if>
            <xacro:if value="${(mirror_dae == True) and (front_hind_dae == True)}">
                <origin rpy="0 0 0" xyz="${kfe_motor_offset_x} ${kfe_motor_offset_y} 0"/>
            </xacro:if>
            <xacro:if value="${(mirror_dae == False) and (front_hind_dae == False)}">
                <origin rpy="0 0 0" xyz="${-kfe_motor_offset_x} ${-kfe_motor_offset_y} 0"/>
            </xacro:if>
            <xacro:if value="${(mirror_dae == True) and (front_hind_dae == False)}">
                <origin rpy="0 0 0" xyz="${-kfe_motor_offset_x} ${kfe_motor_offset_y} 0"/>
            </xacro:if>
            <parent link="${name}_lowerleg"/>
            <child link="${name}_kfe_motor"/>         
        </joint>
        
        <link name="${name}_kfe_motor">
            <!--visual>
                <origin rpy="0 ${PI/2.0} 0" xyz="0 0 0"/>
                <geometry>
                    <cylinder length="0.02" radius="0.035"/>
                </geometry>
                <material name="green"/>
            </visual>
            <collision>
                <origin rpy="0 ${PI/2.0} 0" xyz="0 0 0"/>
                <geometry>
                    <cylinder length="0.02" radius="0.035"/>
                </geometry>
            </collision -->
            <inertial>
                <origin rpy="0 0 0" xyz="${motor_com_x} ${motor_com_y} ${motor_com_z}"/>
                <mass value="${motor_mass}"/>
                <inertia
                    ixx="${motor_ixx}" ixy="${motor_ixy}" ixz="${motor_ixz}"
                    iyy="${motor_iyy}" iyz="${motor_iyz}"
                    izz="${motor_izz}"/>              
            </inertial>
         </link>

        <joint name="${name}_foot_fixed" type="fixed">
            <origin rpy="0 0 0" xyz="0 0 ${-(lowerleg_length)}"/>
            <parent link="${name}_lowerleg"/>
            <child link="${name}_foot"/>
        </joint>

        <link name="${name}_foot">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <sphere radius="${foot_radius-0.01}"/>
                </geometry>
                <!-- <material name="orange"/> -->
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <sphere radius="${foot_radius}"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="${foot_mass}"/>
                <inertia
                    ixx="${(2*foot_mass)/5.0*(foot_radius*foot_radius)}" ixy="0.0" ixz="0.0"
                    iyy="${(2*foot_mass)/5.0*(foot_radius*foot_radius)}" iyz="0.0"
                    izz="${(2*foot_mass)/5.0*(foot_radius*foot_radius)}"/>             
            </inertial>
        </link>

        <!-- Extensions -->
        <xacro:leg_transmission name="${name}"/>
        <xacro:leg_gazebo name="${name}" load_force_sensors="${load_force_sensors}"/>
    </xacro:macro>
</robot>
